# This workflow will build a .NET project
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # CHANGE THIS: Ubuntu cannot handle Windows Multimedia libraries
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    # ADD THIS: This actually runs the compiler to check for errors
    - name: Build
      run: dotnet build --no-restore
